### ISSUE TITLE
Solver returning NaN for polytope

### ISSUE THREAD

**Issue by tjltjl** [kevin-tracy/dpax#5]
I get something like this about 1% of the time when going through a trajectory.

I also saw a case where there was a NaN only when vmapping with a neighbor, when vmapping by itself, it returned a reasonable value but I'd say this is the more urgent thing to deal with. 

As a reasonably simplified case, running
```
case = """
{'A1': array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [-1., -0., -0.],
       [-0., -1., -0.],
       [-0., -0., -1.]], dtype=float32), 
'A2': array([[ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00, -1.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 1.0000000e+00,  6.1232343e-17,  0.0000000e+00],
       [ 1.2246469e-16, -1.0000000e+00,  0.0000000e+00],
       [-1.0000000e+00, -1.8369701e-16,  0.0000000e+00]], dtype=float32), 
'Q1': array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32),
'Q2': array([[ 0.7862767 ,  0.56323767,  0.25403085],
       [ 0.37779117, -0.11291765, -0.91897917],
       [-0.48891932,  0.8185428 , -0.30157077]], dtype=float32), 
'b1': array([250,  10, 100, 250,  10,   0], dtype=int32), 
'b2': array([ 10.,   0., 135., 135., 135., 135.], dtype=float32), 
'r1': array([ 500.,  240., -240.], dtype=float32), 
'r2': array([443.53207, 122.23459, -95.82329], dtype=float32)}
"""

dpax.polytopes.polytope_proximity(**eval(case))
```

returns NaN

![image](https://github.com/kevin-tracy/dpax/assets/2869853/b89538c4-b2c6-43ad-b60d-da7851d5cbc2)

I'm not going to be able to contribute a solution here; I'll happily test further if you have a solution but without one, I have to turn to other methods

**Comment by kevin-tracy** [comment]
Thank you for updating this. I am going to be busy until next week, but after that I think I can figure out a solution. 

Ideally I would like to use some active-set tricks such that you can specify a bunch of constraints, then an have a mask vector that communicates which of these is actually considered in the problem. 

Sorry for any frustration this has caused you.

**Comment by kevin-tracy** [comment]
Actually, with jax 0.4.20 in colab I am able to solve the above problem. 

I get `Array(1.8859866, dtype=float32)`.

**Comment by tjltjl** [comment]
Update: I get the same output for the case above on linux on the CPU.

However, there is still some instability in play: this is the curve I get for the output of moving a primitive close to another one:

![image](https://github.com/kevin-tracy/dpax/assets/2869853/8f7eb4be-5803-4a95-a263-f01922a9e91e)

As you can imagine, the higher-level optimizer finds the situation confusing (small steps in location of the path produce huge noisy changes in the objective function).

If I understand the DSOL algorithm correctly, it shouldn't be doing this, right? The derivative can be discontinuous (two long objects next to each other) but not the value...

So there are two separate issues now: 1) the difference between mac and linux (could be jax, could be scipy, could be something else), 2) the instability in the solver given slightly different positions as input.

If the output is supposed to be continuous, I think one thing to try would be to make a hypothesis test to randomly exercise the algorithm and check that tiny changes in position do not cause huge changes in the output. If the above assumption is true and you plan to figure out a fix, I can contribute such a test.

**Comment by tjltjl** [comment]
(hypothesis as in the python randomized testing framework, that is)

**Comment by tjltjl** [comment]
I found a bug in my constraints, the sign of b was flipped in one place so that would make the problem non-convex.

Being able to detect that would be a really nice-to-have but now it seems to work correctly on linux. Possibly also on the mac, it can well be that the non-convexity exercised some other less significant bug there.

But now it seems I can proceed.

Apologies for the user error and thank you!

**Comment by tjltjl** [comment]
..turns out working around it isn't easy: handling nans post facto in reverse mode autodiff is non-trivial (basically we'd have to run dpax twice and also propagate the gradients...).

So I searched on and finally:

***found it***. It's the cholesky decomposition failing because the matrix is ever so slightly not positive semidefinite.

The result of eigh on the matrix are
(array([-3.8822232e-06,  7.2244270e+01,  1.2889648e+03,  1.6344698e+06],
       dtype=float32),

so this is in the order of magnitude where it's brought on by rounding errors of a positive semidefinite matrix. This means that the comment in the solver re regularization is apt.

I'll try adding some identity matrix to the argument of cholesky decomposition (something like a millionth of the largest absolute matrix element value) and see if that fixes things enough to proceed

**Comment by tjltjl** [comment]
Looks so far so good! Seems to be working without NaNs, still need to verify that it's actually doing the right thing

**Comment by kevin-tracy** [comment]
Thanks for tracking this down, sorry for the annoyance. In my general purpose qp solver, I use QR to solve the linear systems, which is much better numerically for single precision (https://github.com/kevin-tracy/qpax/blob/main/qpax/pdip.py#L12), and can handle any slightly negative eigenvalues. 

I should really get qpax registered on pip and use it in this package.

**Comment by kevin-tracy** [comment]
closed
